// ---------------------------------------------------------------------------
// CLI: generate — run codegen to produce types.ts + client.ts
// ---------------------------------------------------------------------------

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve, relative } from 'node:path';
import type { SchemaDefinition } from '../schema/types.js';
import { generateTypes } from '../codegen/types.js';
import { generateClient } from '../codegen/client.js';
import { loadSchema } from './loader.js';
import { pullSchemaFromServer } from './generate_helpers.js';
import { log } from './log.js';

export interface GenerateOptions {
  schema?: string;
  output: string;
  fromServer?: boolean;
  url?: string;
  token?: string;
  email?: string;
  password?: string;
}

export async function generate(opts: GenerateOptions & { quiet?: boolean }): Promise<void> {
  const timer = log.timer();
  let schema: SchemaDefinition;

  if (!opts.quiet) log.step('GENERATE');

  if (opts.fromServer) {
    if (!opts.url) throw new Error('--url is required when using --from-server');
    log.info('Loading schema from server');
    schema = await pullSchemaFromServer({
      url: opts.url,
      token: opts.token,
      email: opts.email,
      password: opts.password,
    });
  } else {
    const schemaPath = resolve(opts.schema ?? 'pb_schema/schema.ts');
    log.info(`Loading schema from ${schemaPath}`);
    schema = await loadSchema(schemaPath);
  }

  const collectionNames = Object.keys(schema);
  log.info(`Generating types for ${collectionNames.length} collection(s)`);
  log.collections(collectionNames);

  const outDir = resolve(opts.output);
  mkdirSync(outDir, { recursive: true });

  // Generate types.ts
  const typesSource = generateTypes(schema);
  const typesPath = resolve(outDir, 'types.ts');
  writeFileSync(typesPath, typesSource, 'utf-8');
  log.file(relative(process.cwd(), typesPath));

  // Generate client.ts
  const clientSource = generateClient(schema);
  const clientPath = resolve(outDir, 'client.ts');
  writeFileSync(clientPath, clientSource, 'utf-8');
  log.file(relative(process.cwd(), clientPath));

  // Generate index.ts barrel
  const indexSource = [
    `// Auto-generated by pocketforge — DO NOT EDIT`,
    `export * from './types.js';`,
    `export { createClient, type TypedPocketBase, type TypedRecordService } from './client.js';`,
    '',
  ].join('\n');
  const indexPath = resolve(outDir, 'index.ts');
  writeFileSync(indexPath, indexSource, 'utf-8');
  log.file(relative(process.cwd(), indexPath));

  if (!opts.quiet) log.done('Types generated', timer.elapsed());
}
