// ---------------------------------------------------------------------------
// Code generator: Schema → Typed PocketBase client wrapper
// ---------------------------------------------------------------------------

import type { SchemaDefinition } from '../schema/types.js';

function collectionTypeName(name: string): string {
  const pascal = name
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase());
  return `${pascal}Record`;
}

function collectionCreateTypeName(name: string): string {
  const pascal = name
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase());
  return `${pascal}Create`;
}

function collectionUpdateTypeName(name: string): string {
  const pascal = name
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase());
  return `${pascal}Update`;
}

function safePropName(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

// ---------------------------------------------------------------------------
// Generate the client.ts file
// ---------------------------------------------------------------------------

export function generateClient(schema: SchemaDefinition): string {
  const names = Object.keys(schema);
  const blocks: string[] = [];

  // Header
  blocks.push(`// Auto-generated by pocketforge — DO NOT EDIT`);
  blocks.push(`// Generated at: ${new Date().toISOString()}`);
  blocks.push('');

  blocks.push(`import PocketBase from 'pocketbase';`);
  blocks.push(`import type { RecordService, RecordOptions } from 'pocketbase';`);
  blocks.push(`import type {`);
  for (const name of names) {
    blocks.push(`  ${collectionTypeName(name)},`);
    const def = schema[name]!;
    if (def.type !== 'view') {
      blocks.push(`  ${collectionCreateTypeName(name)},`);
      blocks.push(`  ${collectionUpdateTypeName(name)},`);
    }
  }
  blocks.push(`} from './types.js';`);
  blocks.push('');

  // TypedRecordService — wraps RecordService with typed create/update
  blocks.push(`export interface TypedRecordService<`);
  blocks.push(`  R,`);
  blocks.push(`  Create = R,`);
  blocks.push(`  Update = Partial<Create>,`);
  blocks.push(`> extends Omit<RecordService<R>, 'create' | 'update'> {`);
  blocks.push(`  create(bodyParams: Create | FormData, options?: RecordOptions): Promise<R>;`);
  blocks.push(`  update(id: string, bodyParams: Update | FormData, options?: RecordOptions): Promise<R>;`);
  blocks.push(`}`);
  blocks.push('');

  // TypedPocketBase interface with overloaded collection()
  blocks.push(`export interface TypedPocketBase extends PocketBase {`);
  for (const name of names) {
    const recordType = collectionTypeName(name);
    const def = schema[name]!;
    if (def.type === 'view') {
      blocks.push(`  collection(idOrName: ${JSON.stringify(name)}): TypedRecordService<${recordType}>;`);
    } else {
      const createType = collectionCreateTypeName(name);
      const updateType = collectionUpdateTypeName(name);
      blocks.push(`  collection(idOrName: ${JSON.stringify(name)}): TypedRecordService<${recordType}, ${createType}, ${updateType}>;`);
    }
  }
  // Fallback for unknown collection names
  blocks.push(`  collection(idOrName: string): RecordService;`);
  blocks.push(`}`);
  blocks.push('');

  // createClient factory
  blocks.push(`/**`);
  blocks.push(` * Create a typed PocketBase client.`);
  blocks.push(` *`);
  blocks.push(` * @param url - PocketBase server URL (e.g. "http://localhost:8090")`);
  blocks.push(` * @returns A PocketBase client with full type safety for all collections`);
  blocks.push(` */`);
  blocks.push(`export function createClient(url: string): TypedPocketBase {`);
  blocks.push(`  return new PocketBase(url) as TypedPocketBase;`);
  blocks.push(`}`);
  blocks.push('');

  return blocks.join('\n');
}
